version: '3.7'

services:
  career-center-api:
    image: ozcey/career-center-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
    networks:
      - career-center-api-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER:  ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB:  ${DB_NAME}
    volumes:
      - career-db-volume:/var/lib/postgresql/data
    networks:
      - career-center-api-network

volumes:
  career-db-volume:

networks:
  career-center-api-network: