spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev


server:
   port: 5000
   servlet:
     context-path: /career-center/api
   tomcat:
     relaxed-query-chars: '|,{,},[,]'


app:
  jwtSecret: ${JWT_SECRET}
  jwtExpiration: ${JWT_EXPIRATION}
  allowedOrigins: ${ALLOWED_ORIGINS}
