spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev



server:
  port: 5000
  servlet:
    context-path: /career-center/api
  tomcat:
    relaxed-query-chars: '|,{,},[,]'


app:
  jwtSecret: iUBL00R20q4PFDnM6BdTC3bC84O
  jwtExpiration: 604800000
  allowedOrigins: http://localhost:4200

  
 
