spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${ACTIVE_PROFILE}

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpiration: ${JWT_EXPIRATION}
  allowedOrigins: ${ALLOWED_ORIGINS}
