# configs for docker
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    platform: postgres
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: false
      
server:
   port: 5000
   servlet:
     context-path: /career-center/api

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpiration: ${JWT_EXPIRATION}
  allowedOrigins: ${ALLOWED_ORIGINS}
